AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  function5B4675E7:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function5B4675E7
      Description: !Sub
        - Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName} Function ${ResourceName}
        - ResourceName: deployFrontEnd
      CodeUri: src/deployFrontEnd
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 300
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - S3CrudPolicy:
            BucketName: !Ref objectStore86870FA0
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObjectAcl
              Resource:
                - !Sub ${objectStore86870FA0.Arn}/*
      Environment:
        Variables:
          BUCKET_NAME: !Ref objectStore86870FA0
          BUCKET_ARN: !GetAtt objectStore86870FA0.Arn
          XDG_CONFIG_HOME: /tmp/.config
      Events:
        tableF505F6E3:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt tableF505F6E3.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
    Metadata:
      StackeryName: deployFrontEnd
  objectStore86870FA0:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-objectstore86870fa0
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    Metadata:
      StackeryName: React App Host
  tableF505F6E3:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-tableF505F6E3
Parameters:
  StackeryStackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  StackeryEnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)